a = (input('Digite um valor '))
print(type(a))
print('O valor é Numerico? ',a.isnumeric())
print('O valor é Alfabeto? ',a.isalpha())
print('O valor está em Maiusculo? ',a.isupper())
print('O valor está em Minusculo? ',a.islower())
print('O valor tem espaço? ',a.isspace())
print('O valor possui numeros ou letras? ',a.isalnum())
print('O valor está "capitalizado", ou seja, maiusculo e minusculo? ',a.istitle())